### PR TITLE
Update to pyamg 3.2.1 and rerender

### PR DESCRIPTION
**Pull request by c-f-h**

### CODE REVIEW

**Comment by c-f-h** [comment]
This appears to work now. Waiting for someone to review it.

CC @jakevdp

**Comment by jakevdp** [comment]
Looks good – thanks! One thing, I think that the build number should be set back to zero in this case, because the package version is updated: https://github.com/conda-forge/pyamg-feedstock#updating-pyamg-feedstock

**Comment by jakevdp** [comment]
Also, I believe that the preference is to not run the full unit test suite in the test phase, because it eats up so many CI resources. Simply confirming that the package imports is usually enough.

**Comment by jakevdp** [comment]
But if the test suite does not take long to run, we can leave the full tests here.

**Comment by c-f-h** [comment]
Reset the build number.

The test suite only seems to take around a minute to run, so I think it's ok. There doesn't seem to be a way to make the `pyamg.test` runner selectively run tests.

If you merge this, please do squash the commit history because I made quite a mess of it :D

**Comment by jakevdp** [comment]
OK – I organized & squashed commits and opened a new PR at #8.

Once CI passes there I'll merge. Thanks for the contribution!

**Pull request closed without merging**
