### PR TITLE
Rerender & Update to 3.2.1

### PR DESCRIPTION
**Pull request by jakevdp**
Replaces #7

### CODE REVIEW

**Comment by c-f-h** [comment]
Hm. It finally started building after many hours and then it was canceled?

**Comment by jakevdp** [comment]
I restarted the cancelled jobs. Hopefully it makes it through...

**Comment by c-f-h** [comment]
Nice. Worked now!

**Comment by jakevdp** [comment]
Great – thanks for all the work on this!

**Pull request merged**
