### PR TITLE
MNT: Rerender to remove old compilers

### PR DESCRIPTION
**Pull request by xhochy**
@conda-forge-admin please rerender

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jschueller** [comment]
maybe remove the verbosity option in run_test.py to pass the log limit ?

**Comment by jschueller** [comment]
maybe invoking pytest manually instead of using run_test.py ?
https://github.com/pyamg/pyamg/blob/master/pyamg/__init__.py#L57

**Comment by jschueller** [comment]
I tried to redirect pytest output in #20 but the build fails with some others errors due to libgfortran now...

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge/pyamg This is finally green and ready for review.

**Review by jschueller — APPROVED** [review]
+1, please merge

**Comment by scopatz** [comment]
@xhochy @jschueller - merging because this seems to be abandoned, but if you  sould please consider adding yourselves as maintainers that would be great!

**Pull request merged**
